version: '3'
services: 
  nginx-app:
    build: ./Docker-Nginx
    container_name: nginx-app
    hostname: nginx-app
    restart: always
    volumes:
      - ${PROJECT_PATH}:/var/www/demo
      - .\data\nginx\conf.d\:/etc/nginx/conf.d
    ports: 
      - "80:80"
      - "443:443"
  php-fpm-app:
    build: ./Docker-PHP-FPM
    container_name: php-fpm-app
    hostname: php-fpm-app
    restart: always
    volumes:
      - ${PROJECT_PATH}:/var/www/demo
    ports:
      - "9000:9000"
  mysql-app:
    build: ./Docker-MySQL
    container_name: mysql-app
    hostname: mysql-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - mysql-app-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-app-data: