version: '3'
services: 
  nginx-PROJECTNAME:
    build: ./Docker-Nginx
    container_name: nginx-${PROJECT_NAME}
    hostname: nginx-${PROJECT_NAME}
    restart: always
    volumes:
      - "default-PROJECTNAME:/var/www/${PROJECT_NAME}:nocopy"
      - ./data/nginx/conf.d/:/etc/nginx/conf.d
    ports: 
      - "80:80"
      - "443:443"
  php-fpm-PROJECTNAME:
    build: ./Docker-PHP-FPM
    container_name: php-fpm-${PROJECT_NAME}
    hostname: php-fpm-${PROJECT_NAME}
    restart: always    
    volumes:
      - "default-PROJECTNAME:/var/www/${PROJECT_NAME}:nocopy"        
      - ./data/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /var/www/${PROJECT_NAME}
    expose:
      - "9001"
    environment:
      XDEBUG_ENABLE: "off" # Set 'on' for general xdebug use
      XDEBUG_REMOTE_ENABLE: "off"
      XDEBUG_PROFILER_ENABLE: "off"
      XDEBUG_HOST_ADDRESS: "10.0.75.1"
  mysql-PROJECTNAME:
    build: ./Docker-MySQL
    container_name: mysql-${PROJECT_NAME}
    hostname: mysql-${PROJECT_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - mysql-${PROJECT_NAME}-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-PROJECTNAME-data:
  default-PROJECTNAME:
    external: true